version: "3"
services:
  backend:
    build: ./backend
    container_name: "backend"

  frontend:
    build: ./frontend
    container_name: "frontend"
    depends_on:
      - backend
  proxy:
    build: ./nginx
    container_name: "fullstack-proxy"
    restart: always
    ports:
      - "80:80"